### ISSUE TITLE
The paper

### ISSUE THREAD

**Issue by maybeluo** [uclmr/low-rank-logic#2]
I'm wondering if you can public your paper as soon as possible, if your camera ready version for NAACL-HLT 2015 is done. Eager to see it. Many thanks

**Comment by sameersingh** [comment]
Still working on it, we'll upload it when it's done. Thanks for your interest!

**Comment by maybeluo** [comment]
Looking forward to seeing it. Thanks a lot

**Comment by maybeluo** [comment]
I'm missing your paper~

**Comment by rockt** [comment]
It's now uploaded [here](https://github.com/rockt/rockt.github.com/blob/master/pdf/rocktaschel2015injecting.pdf).

**Comment by maybeluo** [comment]
I have almost the same idea since three months ago and have done some experiments. That's why I'm eager to see your paper. Thanks for your replies. I really like your work and congratulations!
