### ISSUE TITLE
Where to find ml.wolfe

### ISSUE THREAD

**Issue by maybeluo** [uclmr/low-rank-logic#3]
When I read code in ''MatrixFactorization.scala", a lot of functions are called, e.g. toFactorGraph, fg.buildStochasticFactor, CellLogisticLoss etc. But I can't find the implementation of these functions, even when I search the names of these function in Wolfe. 
Where can I find the implementation of these functions? Many thanks.

**Comment by maybeluo** [comment]
One more question about #L143 in the file, fg.buildStochasticFactor(Seq(c, db.sampleNodeFrom2(colIx))), what's the function of  db.sampleNodeFrom2 ?

**Comment by rockt** [comment]
Hi maybeluo, toFactorGraph is here: https://github.com/uclmr/low-rank-logic/blob/master/src/main/scala/uclmr/TensorDB.scala#L226
CellLogisticLoss is here (note that this porject depends of Wolfe v0.4): https://github.com/wolfe-pack/wolfe/blob/v0.4.0/wolfe-core/src/main/scala/ml/wolfe/fg/CellLogisticLoss.scala
db.sampleNodeFrom2 is here: https://github.com/uclmr/low-rank-logic/blob/master/src/main/scala/uclmr/TensorDB.scala#L341

**Comment by maybeluo** [comment]
Thanks, and sorry for my negligent.

**Comment by rockt** [comment]
No worries, I guess the setup is not very intuitive :) Cheers, Tim
